# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b3020281f10372875e7623292b13d3e0f86db0ce5cf739a8534adf2a800d9e0f0a3fd336479c8035f80c7920a0a2fb9f37795211262946ec91c8cb2c9fc235d

test:
  secret_key_base: 05678e4c3a0134c5921551a6c68c2e5d23ec7f94295c90f1c4ee7807d8006a2eba42bb3c1ced0043f06d2292cd116c425c0ae02b0b0653868a769407459b60a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
